// src/data/menuData.js
export const menuData = [
  { id: 1, 
    name: '經典可頌', 
    price: 40, 
    image: 'img/bread/croissant.jpg', 
    description:'我們的 經典可頌 採用 進口法國AOP認證奶油 與 高品質麵粉，經過 三折六疊工法，手工反覆摺疊出 27 層 的酥脆層次。每一口都帶有濃郁的奶香與微微焦糖化的香氣，外酥內嫩，口感細膩有層次。' },
  { id: 2, 
    name: '經典肉桂捲', 
    price: 50, 
    image: 'img/bread/cinnamon_rolls.jpg', 
    description:'我們的經典肉桂捲選用 純手工揉製 的麵糰，經過長時間低溫發酵，使口感更加鬆軟濕潤。內餡使用 斯里蘭卡頂級肉桂粉，    搭配香甜焦糖與法國進口奶油，完美呈現濃郁的肉桂香氣，每一口都充滿溫暖療癒的風味。'},
  { id: 3, 
    name: '山形吐司', 
    price: 80, 
    image: 'img/bread/plain_white_toast.jpg', 
    description:'我們的 山形吐司 採用 嚴選高品質小麥粉，經過 低溫長時間發酵，讓麵包內部形成細膩柔軟的結構，外皮則呈現金黃微脆的完美口感。以 純鮮奶與天然奶油 製作，不添加人工香料與防腐劑，讓你吃得安心又健康。'},
  { id: 4, 
    name: '蘋果麥香麵包', 
    price: 80, 
    image: 'img/bread/apple_bread.jpg', description:'我們的 蘋果麥香麵包 採用 高纖全麥麵粉，搭配 新鮮蘋果丁 及 天然蜂蜜，經過 長時間低溫發酵，讓口感更加濕潤綿密，帶有淡淡的麥香與蘋果的自然甜味。這款麵包不僅健康美味，更是早餐或下午茶的最佳選擇！'},
  { id: 5, 
    name: '香蕉蛋糕', 
    price: 80, 
    image: 'img/bread/banana_cake.jpg', 
    description:'我們的 香蕉蛋糕 採用 新鮮熟成香蕉 製作，不添加人工香精，讓你品嚐到最純粹的香蕉甜香。搭配 法國進口奶油與天然蜂蜜，使蛋糕口感濕潤綿密，入口即化，甜而不膩。無論是搭配咖啡、茶，或是單吃，都是令人回味無窮的經典甜點！'},
  { id: 6, 
    name: '芝麻饅頭', 
    price: 30, 
    image: 'img/bread/sesame_bun.jpg', 
    description:'我們的 芝麻饅頭 採用 精選黑芝麻研磨粉，搭配 高品質中筋麵粉與天然酵母，經過 長時間發酵，讓口感更加Q彈有嚼勁。每一口都能感受到濃郁的芝麻香氣，既營養又美味，是早餐、下午茶或搭配料理的完美選擇！'}
];
